### ISSUE TITLE
Use default locale without language prefix

### ISSUE THREAD

**Issue by C10ne** [Martimiz/silverstripe-languageprefix#7] opened 2013-09-25 11:37 UTC
Is it possible to set up the module to use the default locale when there is no language prefix?

For example, if I enter mysite.com/page/, and the default locale is en_US, it would display mysite.com/en_US/page.

Hope you understand what I need, since it's important for SEO.

Thanks,
    Ivan

**Comment by andreaslindahl** [comment] 2015-05-08 17:58
Is there a good solution for this problem? I have two languages configured, and since Swedish is the main language, and the English version of the site just as a bonus, I would like the default language pages to use URLs without a language prefix.

**Comment by andreaslindahl** [comment] 2015-05-08 17:59
Is there some other module that manages to solve this?

**Comment by Martimiz** [comment] 2015-05-08 18:09
I don't know about any other modules that would support this. I was hoping someone would come up with a good starting point for this, because unfortunately at this moment I don't have the time available to delve into this...

Also I'm not quite convinced - can someone please explain to me why this would be a good thing?

**Comment by andreaslindahl** [comment] 2015-05-08 18:15
In my case, the Swedish version is the main version. Probably 95% of all visitors will want to access the Swedish version. Therefore, it's convenient and a better user experience to have URLs without the language code. It's shorter, easier to remember individual URLs. And it's cleaner. Basically I would like the Swedish version of the site to behave like just any normal Silverstripe site when it comes to URLs and have the English version below /en.

**Comment by quinnmerio** [comment] 2015-05-08 18:24
With the most recent build of silverstripe and translatable module, it
already appears to do this out of the box. Unique urls, without any
language prefix at all.

**Comment by Martimiz** [comment] 2015-05-08 18:29
I'm not sure if I understand you correctly but in Translatable it has always been possible to have multiple languages without using prefixes. The languageprefix module was created for people that wanted to use them...

**Comment by andreaslindahl** [comment] 2015-05-08 18:30
Which build are you referring to? The build I'm using adds the locale to the end of the URLSegment

**Comment by quinnmerio** [comment] 2015-05-08 18:35
I may be assuming url . it adds the locale as a query string param to the
end of the url in the admin only. But not in the front end of the site.

I am using "silverstripe/cms": "3.1.12", "silverstripe/translatable":
"2.0.*"

I have ditched the silverstripe-languageprefix module altogether.

**Comment by andreaslindahl** [comment] 2015-05-08 18:37
So what URLs do you get on the front end site?

**Comment by quinnmerio** [comment] 2015-05-08 18:39
I browse to /about-us and see the site tree menu for all pages set as
english.
I browse to /a-propos-de-nous  and see the site tree for all french pages.

**Comment by andreaslindahl** [comment] 2015-05-08 18:41
Ah, ok. The thing is I would like to have the French version at /fr/a-propos-de-nous instead, while the english version will be located at /about-us.

**Comment by quinnmerio** [comment] 2015-05-08 18:50
Yep. that is what i wanted, also. And i never found a good way to do that.
I opted to explain to clients that we simply did not need the /fr in front,
seeing as all the urls were unique anyways.  On the home page for french, I
simply made the url segment "fr".  So you hit /fr and it goes to french
home.  Every other page was just a regular page with french urls. I now see
no added benefit of adding /fr in front of the main url :)

**Comment by Martimiz** [comment] 2015-05-08 18:51
@quinnmerio - as I said: no reason to use it if you do not need it. Ditch doesn't sound very nice though :(

@andreaslindahl - it would have to be a bit of a rewrite, because the module expects the prefix (see PrefixModelAsControler ~ #34. 

It would have to be optional, because links would either have to be generated with or without prefix for the default language...

**Comment by Martimiz** [comment] 2015-05-08 18:54
I'll try and have a look on monday to see if it's at least feasible.

**Comment by andreaslindahl** [comment] 2015-05-08 18:56
That would be awesome! :)

**Comment by quinnmerio** [comment] 2015-05-08 18:59
Perhaps ditch isn't the right word.. ;-) .. opted to not use.

**Comment by Martimiz** [comment] 2015-05-12 13:50
I've set up a test branch called 'no-prefix-for-default'. By adding the following config setting in /languageprefix/_config/languageprefix.yml (and flush):

      prefixconfig:
        ...
        disable_prefix_for_default_lang: true

It should: skip the prefix for the Default Translatable locale, perform a permanent redirect for links that still use it, and update the links in the CMS URLSegment field. The alternative links in the header also work.

I would appreciate it if you would test this (think forms, images, etc) 

Martine

**Comment by andreaslindahl** [comment] 2015-05-13 06:58
Great! I will give it a try ASAP!

**Comment by andreaslindahl** [comment] 2015-05-13 08:35
Hi

Form actions doesn't seem to work. I get a 404...

**Comment by Martimiz** [comment] 2015-05-13 12:31
Yes I see - it is harder then I thought:  basically this testversion doesn't support subpages nor actions, so it is sort of useless so far :( 

I would have to subclass the ContentController to change the request handler, and that is not an option at this point. I'll think about another way, but for now - sorry...

**Comment by andreaslindahl** [comment] 2015-05-13 13:03
No problem! I'm glad you gave it a try!

**Comment by Martimiz** [comment] 2015-05-28 16:11
I've uploaded a new version of the 'no-prefix-for-default' branch. It is a bit of a rewrite, because the original version could not be persuaded to do this. So it definitely needs testing, especially with the subsites module. 

@andreaslindahl: If you are still interested, please let me know if you can do some of the testing?

**Comment by andreaslindahl** [comment] 2015-05-28 16:39
I would be happy to test it!

**Comment by Martimiz** [comment] 2015-05-28 17:00
well, it's ready for download, just not for production yet. Let me know :)

**Comment by andreaslindahl** [comment] 2015-05-28 17:01
Yup, I downloaded and have tested it. So far everything seems to work as it should, including forms. :)

**Comment by Martimiz** [comment] 2015-05-28 17:51
Well, that's a start :) basically now it's about what should happen with all kinds of urls. For instance if you disable the prefix for the default language 'en', links that have /en/ in them get 301 redirected to the links without prefix. But there can be all kinds of other options.

For instance what happens the other way around, what happens with older links, what happens to, say, french pages called without prefix, etc. Easy to just generate 404's, but what kind of support for 'wrong' or older links would be necessary from a SEO point of view? These are serious questions :)

**Comment by andreaslindahl** [comment] 2015-10-03 21:31
Hi again :)

Found a bug. BaseLinkForLocale() doesn't seem to work. I believe the reason is this line (#203):

$prefix = LanguagePrefix::get_prefix();

Changed it to

$prefix = LanguagePrefix::get_prefix($this->owner->Locale);

and got it working

**Comment by Martimiz** [comment] 2015-10-04 09:05
Yes I can see that this is a bug, because it will alwas set the BaseLinkForLocale to the default locale. Thanks for spotting it! Care to create a pull request?

**Comment by Martimiz** [comment] 2015-10-05 08:19
Thanks, merged. 

Have you found this version working as it should otherwise? I'd like to make this the master branch, and I don't see any problems myself, but as it's a substantial rewrite, I'd like to be as sure as possible :)

**Comment by andreaslindahl** [comment] 2015-10-05 08:45
So far it seems to work perfectly. You should perhaps get someone else to test it as well, however. I have only used it on a very small website, with just two languages, so far.

**Comment by Martimiz** [comment] 2015-10-05 09:02
I don't think having two or ten languages, nor two or a hundred pages would really make a difference - the basics are the same. Further more it's alle about page urls. My only worries were things like forms and homepages, but they seem to work fine now.

Other problems might be caused by modules that extend the Link functionality in a non-standard way, but I think that's outside the scope of this module.

Would be nice if other people would test it too, but unfortunately I can't reach out to people other then asking it here :) And I don't really know how big the target audience for this mod is anyway, that's another thing... 

But thanks for pointing out bug(s) :)

Cheers, Martine

**Comment by axyr** [comment] 2016-04-22 18:18
can you merge this to master and tag it?

seems to work here very welll.

**Comment by Martimiz** [comment] 2016-05-18 16:59
I've moved the current version to a separate branche 2.0, and taggedit as 2.0.0. I'm doing some final tests on the new version after upgrading to PSR-2 and I will shortly release it as v3.0.0

**Comment by Martimiz** [comment] 2016-05-19 10:11
The new version is now released as v3.0.0

**Closed by Martimiz** 2016-05-19 10:11 UTC
